[appearance]
scale = 20
color_foreground = 16777215
color_background = 0
is_pixel_style = true
operations_per_second = 800
sound_volume = 0.1

[quirks]
vf_reset = true
memory = false
shifting = true
jumping = false
